apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gcr-poc-today-detail-page-view
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - bash
            - -c
            - |
              set -euxo pipefail
              ./tpt/google/today_detail-page-view.sh
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS__B64
              valueFrom:
                secretKeyRef:
                  key: b64
                  name: gcp-gcr-poc
            image: teacherspayteachers/python-etl:bk
            imagePullPolicy: Always
            name: gcr-poc
            resources:
              limits:
                cpu: "1"
                memory: 2Gi
              requests:
                cpu: "1"
                memory: 2Gi
          imagePullSecrets:
          - name: tptreadonly-docker
          restartPolicy: OnFailure
  schedule: 0 */6 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
